config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord

  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save cat_params
      redirect_to cats_path
    else
      redirect_to new_cat_path
    end
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cats_path
    else
      redirect_to new_cat_path
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy!
    redirect_to cats_path
  end

  private def cat_params
    params.require(:cat).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/edit.html.erb
<h1> Edit the root of evil that is a cat! </h1>
<%= simple_form_for @cat do |form| %>
  Update Name: <%= form.text_field :name %></br>
  Update Description: <%= form.text_field :description %></br>
  Update details: <%= form.submit %>
<% end %>

app/views/cats/index.html.erb
<h1> My fabulous list of all the cats</h1>
</br>
<section>
  <% @cats.each do |cat| %>
    <%= cat.name %> - - 
    <%= cat.description %></br>
    <%= link_to "Show me this so called cat.", cat_path(cat.id) %><br />
    <%= link_to "Update this feline.", edit_cat_path(cat.id) %><br />
    <%= link_to "Annihilate this moggy.", cat_path(cat.id), method: :delete %><br />
    ------------------------------------<br />
  <% end %>
  <%= link_to "Create a new Cat", new_cat_path %>
</section>

app/views/cats/new.html.erb
<h1> Create your next utter bastard of a feline</h1>
</br>
<section>
  <%= simple_form_for @cat do |form| %>
    Name: <%=  form.text_field :name %></br>
    Description: <%= form.text_field :description %></br>
    Save the Bastard! <%= form.submit %>
  <% end %>
  <%= link_to "Back to my cats", cats_path %>
</section>

app/views/cats/show.html.erb
<h1> Here is your bloody cat!!! </h1>
  <%= @cat.name %></br>
  <%= @cat.description %></br>
<%= link_to "Return to cats listings..", cats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YesMoreCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>